package  {
	import flash.utils.ByteArray;

	public class IFDName{
		public static  const TAG_DIC:Object={
		0:new IFDName("GPSVersionID","GPS版本ID"),
		1:new IFDName("GPSLatitudeRef","GPS南北纬度"),
		2:new IFDName("GPSLatitude","GPS纬度数"),
		3:new IFDName("GPSLongitudeRef","GPS东西经度"),
		4:new IFDName("GPSLongitude","GPS经度数"),
		5:new IFDName("GPSAltitudeRef","GPS海拔引用"),
		6:new IFDName("GPSAltitude","GPS海拔"),
		7:new IFDName("GPSTimeStamp","GPS时间戳"),
		8:new IFDName("GPSSatellites","GPS卫星"),
		9:new IFDName("GPSStatus","GPS接收状态"),
		10:new IFDName("GPSMeasureMode","GPS尺度模式"),
		11:new IFDName("GPSDOP","GPS测量精度"),
		12:new IFDName("GPSSpeedRef","GPS速度单位"),
		13:new IFDName("GPSSpeed","GPS速度"),
		14:new IFDName("GPSTrackRef","GPS方向单位"),
		15:new IFDName("GPSTrack","GPS方向"),
		16:new IFDName("GPSImgDirectionRef","GPS图片方向单位"),
		17:new IFDName("GPSImgDirection","GPS图片方向"),
		18:new IFDName("GPSMapDatum","GPS地图数据"),
		19:new IFDName("GPSDestLatitudeRef","GPS目的地南北纬度"),
		20:new IFDName("GPSDestLatitude","GPS目的地纬度数"),
		21:new IFDName("GPSDestLongitudeRef","GPS目的地东西经度"),
		22:new IFDName("GPSDestLongitude","GPS目的地经度数"),
		23:new IFDName("GPSDestBearingRef","GPS目的地相对位置单位"),
		24:new IFDName("GPSDestBearing","GPS目的地相对位置方向"),
		25:new IFDName("GPSDestDistanceRef","GPS目的地相对距离单位"),
		26:new IFDName("GPSDestDistance","GPS目的地相对距离"),
		27:new IFDName("GPSProcessingMethod","GPS技术名称"),
		28:new IFDName("GPSAreaInformation","GPS地点信息"),
		29:new IFDName("GPSDateStamp","GPS日期戳"),
		30:new IFDName("GPSDifferential","GPS修正"),
		256:new IFDName("ImageWidth","图片宽度"),
		257:new IFDName("ImageLength","图片高度"),
		258:new IFDName("BitsPerSample","构成比特数"),
		259:new IFDName("Compression","压缩方案"),
		262:new IFDName("PhotometricInterpretation","象素合成"),
		266:new IFDName("FillOrder","填充顺序"),
		269:new IFDName("DocumentName","文档名"),
		270:new IFDName("ImageDescription","图片信息"),
		271:new IFDName("Make","设备制造商"),
		272:new IFDName("Model","使用设备"),
		273:new IFDName("StripOffsets","图片数据位置"),
		274:new IFDName("Orientation","图片方向"),
		277:new IFDName("SamplesPerPixel","构成数"),
		278:new IFDName("RowsPerStrip","行数/扫描行"),
		279:new IFDName("StripByteCounts","字节数/扫描行"),
		282:new IFDName("XResolution","X分辨率"),
		283:new IFDName("YResolution","Y分辨率"),
		284:new IFDName("PlanarConfiguration","图片数据组成"),
		296:new IFDName("ResolutionUnit","分辨率单位"),
		301:new IFDName("TransferFunction","传输方法"),
		305:new IFDName("Software","软件"),
		306:new IFDName("DateTime","修改日期"),
		315:new IFDName("Artist","创建者"),
		318:new IFDName("WhitePoint","白点染色性"),
		319:new IFDName("PrimaryChromacities","主染色性"),
		342:new IFDName("TransferRange","转移范围"),
		512:new IFDName("JPEGProc","JPEG压缩进程"),
		513:new IFDName("JPEGInterchangeFormat","SOI位置"),
		514:new IFDName("JPEGInterchangeFormatLength","字节数"),
		529:new IFDName("YCbCrCoefficients","颜色空间转移矩阵"),
		530:new IFDName("YCbCrSubSampling","取样比率"),
		531:new IFDName("YCbCrPositioning","颜色空间布置"),
		532:new IFDName("ReferenceBlackWhite","黑白比对"),
		33421:new IFDName("CFARepeatPatternDim","CFA模式定义"),
		33422:new IFDName("CFAPattern","CFA模式"),
		33423:new IFDName("BatteryLevel","电池级别"),
		33432:new IFDName("Copyright","版权"),
		33434:new IFDName("ExposureTime","暴光时间"),
		33437:new IFDName("FNumber","F指数(光圈)"),
		33723:new IFDName("IPTC/NAA","IPTC/NAA指数"),
		34665:new IFDName("Exif IFD Pointer","Exif数据集"),
		34675:new IFDName("InterColorProfile","颜色剖面"),
		34850:new IFDName("ExposureProgram","暴光程序"),
		34852:new IFDName("SpectralSensitivity","光谱灵敏性"),
		34853:new IFDName("GPSInfo","GPS数据集"),
		34855:new IFDName("ISOSpeedRatings","ISO值"),
		34856:new IFDName("OECF","OECF"),
		36864:new IFDName("ExifVersion","Exif版本信息"),
		36867:new IFDName("DateTimeOriginal","原始创建日期"),
		36868:new IFDName("DateTimeDigitized","转为数码数据时间"),
		37121:new IFDName("ComponentsConfiguration","构成配置"),
		37122:new IFDName("CompressedBitsPerPixel","压缩比特/象素"),
		37377:new IFDName("ShutterSpeedValue","快门速度"),
		37378:new IFDName("ApertureValue","光圈"),
		37379:new IFDName("BrightnessValue","]亮度"),
		37380:new IFDName("ExposureBiasValue","暴光曲线"),
		37381:new IFDName("MaxApertureValue","最大光圈"),
		37382:new IFDName("SubjectDistance","目标距离"),
		37383:new IFDName("MeteringMode","测量模式"),
		37384:new IFDName("LightSource","光源"),
		37385:new IFDName("Flash","闪光灯"),
		37386:new IFDName("FocalLength","焦距"),
		37500:new IFDName("MakerNote","设备商附加信息"),
		37510:new IFDName("UserComment","用户评论"),
		37520:new IFDName("SubSecTime","日期(微秒)"),
		37521:new IFDName("SubSecTimeOriginal","创建日期(微秒)"),
		37522:new IFDName("SubSecTimeDigitized","数码化日期(微秒)"),
		40960:new IFDName("FlashPixVersion","Flashpix版本"),
		40961:new IFDName("ColorSpace","颜色空间"),
		40962:new IFDName("PixelXDimension","有效图片宽"),
		40963:new IFDName("PixelYDimension","有效图片高"),
		40963:new IFDName("RelatedSoundFile","相关声音文件"),
		40965:new IFDName("InteroperabilityOffset","互用性标签位置"),
		41483:new IFDName("FlashEnergy","闪光灯电量"),
		41484:new IFDName("SpatialFrequencyResponse","空间响应频率"),
		41486:new IFDName("FocalPlaneXResolution","焦点平面X分辨率"),
		41487:new IFDName("FocalPlaneYResolution","焦点平面分辨率"),
		41488:new IFDName("FocalPlaneResolutionUnit","分辨率单位"),
		41492:new IFDName("SubjectLocation","主题位置"),
		41493:new IFDName("ExposureIndex","暴光顺序"),
		41495:new IFDName("SensingMethod","感应技术"),
		41728:new IFDName("FileSource","文件源"),
		41729:new IFDName("SceneType","场景"),
		41730:new IFDName("CFAPattern","CFA模式"),
		41985:new IFDName("CustomRendered","图片进程"),
		41986:new IFDName("ExposureMode","暴光模式"),
		41987:new IFDName("WhiteBalance","白平衡"),
		41988:new IFDName("DigitalZoomRatio","数码缩放比"),
		41989:new IFDName("FocalLengthIn35mmFilm","等价于35mm焦段的焦长"),
		41990:new IFDName("SceneCaptureType","场景捕捉类型"),
		41991:new IFDName("GainControl","获取控制"),
		41992:new IFDName("Contrast","对比度"),
		41993:new IFDName("Saturation","饱和度"),
		41994:new IFDName("Sharpness","锐度"),
		41995:new IFDName("DeviceSettingDescription","设备设定"),
		41996:new IFDName("SubjectDistanceRange","目标距离范围"),
		42016:new IFDName("ImageUniqueID","图片标示符"),
		50341:new IFDName("PrintIM","印刷数据位置")
		};
		public var cn:String;
		public var en:String;
		
		public function IFDName(en:String, cn:String){
			this.en=en;
			this.cn=cn;
		}
		
		public function toString():String{
			return cn;
		}
	}
}